%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RUN_FIG8                                                             %
%                                                                      %
% This script performs a multiscale analysis of points generated by a  %
% neural network, as shown in Figure 8.                                %
%                                                                      %
% Steps:                                                               %
%   1. A set of points is generated by a neural network.               %
%   2. Three levels of multiscale analysis are performed using the     %
%      decomposition procedure described in the paper.                 %
%   3. The resulting detail coefficients and coarse data are plotted.  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% generate the set of points using a neural network
pred_xy = NN_circles_128pts(1);

% Compute three levels of detail coefficients and plot the results
NSP_2D_padded_decomposition(pred_xy', 3, 'fig8', 1);