%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RUN_FIG10                                                            %
%                                                                      %
% This script performs a multiscale analysis of 32-point circle        %
% approximations generated by a neural network, as shown in Figure 10. %
%                                                                      %
% The neural network is trained to generate 32 points on a circle      %
% centered at a given point. The approximations obtained after 1, 3,   %
% 5, and 7 epochs are compared with a perfect circle, and their        %
% detail coefficients are plotted.                                     %
%                                                                      %
% Steps:                                                               %
%   1. A neural network is trained to generate 32 points centered at   %
%      a given point, and predictions are obtained after 1, 3, 5, and  %
%      7 training epochs.                                              %
%   2. Each approximation is plotted together their corresponding      %
%      perfect circle.                                                 %
%   3. Two levels of multiscale analysis are performed on each set of  %
%      predicted points using the decomposition procedure described    %
%      in the paper.                                                   %
%   4. The resulting detail coefficients are plotted for comparison.   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% generate 32-point circle approximations after 1, 3, 5, and 7 epochs
% and plot each approximation together with the same perfect circle
[pred_epoch1,pred_epoch3,pred_epoch5,pred_epoch7]=NN_circles_32pts();

% perform two levels of multiscale analysis for each prediction and
% plot the resulting detail coefficients 
NSP_2D_padded_decomposition(pred_epoch1, 2, 'fig10', 1);
NSP_2D_padded_decomposition(pred_epoch3, 2, 'fig10', 1);
NSP_2D_padded_decomposition(pred_epoch5, 2, 'fig10', 1);
NSP_2D_padded_decomposition(pred_epoch7, 2, 'fig10', 1);