%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RUN_FIG9                                                              %
%                                                                       %
% This script compares three sets of sampled points with a perfect      %
% unit circle, as shown in Figure 9.                                    %
%                                                                       %
% The examples include a wavy circle, an oscillatory circle, and a      %
% circle generated by the neural network (NN). The deviation of each    %
% set of points from the unit circle is measured and plotted.           %
%                                                                       %
% Steps:                                                                %
%   1. A set of N = 128 sample points is generated from the unit        %
%      circle with a wavy distortion of amplitude sigma = 0.7.          %
%   2. A second set of N = 128 sample points is generated with a        %
%      periodic oscillatory distortion of amplitude sigma = 0.3.        %
%   3. A set of points is generated by the neural network and shifted   %
%      to the appropriate position for comparison with the unit circle. %
%   4. The deviation of each data set from the unit circle is computed  %
%      by evaluating x^2 + y^2 - 1 at each sample point.                %
%   5. The sampled data and their deviations from the unit circle are   %
%      plotted separately for comparison.                               %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% Generate the sampled data

% wavy distortion with amplitude sigma = 0.7
f_samples_semicircle=NSP_2D_get_samples (128,0.7,'wavy'); 

% periodic oscillatory distortion with amplitude sigma = 0.3
f_samples_noisycircle=NSP_2D_get_samples (128,0.3,'base'); 

% generate the neural network data
pred_xy=NN_circles_128pts(0);
% shift the NN-generated circle to the appropriate position
shifted_NN_samples=pred_xy-[4;6];                               
shifted_NN_samples=shifted_NN_samples';

%% measure the deviation from a perfect unit circle
% compute x^2 + y^2 - 1 for each sample point
diff_wavy=sum(f_samples_semicircle.^2,2)-1;
diff_noisy=sum(f_samples_noisycircle.^2,2)-1;
diff_NN=sum(shifted_NN_samples.^2,2)-1;

%{
% plotting the differences along with the samples in the same figure
figure

%% wavy circle
subplot(3,2,1)
% plot a cicrle
f1=@(t) cos(t); f2=@(t) sin(t);   %circle
t_for_f=-pi:2^(-10):pi;
plot(f1(t_for_f),f2(t_for_f),'LineWidth',2)
hold on
% plot the sampled data points
plot(f_samples_semicircle(:,1),f_samples_semicircle(:,2), '.','MarkerSize',10,'Color','r','LineStyle','none')
axis equal

subplot(3,2,2)
plot(diff_wavy)

%% noisy circle
subplot(3,2,3)
% plot a cicrle
f1=@(t) cos(t); f2=@(t) sin(t);   %circle
t_for_f=-pi:2^(-10):pi;
plot(f1(t_for_f),f2(t_for_f),'LineWidth',2)
hold on
% plot the sampled data points
plot(f_samples_noisycircle(:,1),f_samples_noisycircle(:,2), '.','MarkerSize',10,'Color','r','LineStyle','none')
axis equal

subplot(3,2,4)
plot(diff_noisy)

%% NN cicrle
subplot(3,2,5)
% plot a cicrle
f1=@(t) cos(t); f2=@(t) sin(t);   %circle
t_for_f=-pi:2^(-10):pi;
plot(f1(t_for_f),f2(t_for_f),'LineWidth',2)
hold on
% plot the sampled data points
plot(shifted_NN_samples(:,1),shifted_ai_samples(:,2), '.','MarkerSize',10,'Color','r','LineStyle','none')
axis equal

subplot(3,2,6)
plot(diff_NN)
%}

% plotting the differences along with the samples in different figures

%% plot the wavy circle

figure

% plot the perfect unit cicrle
f1=@(t) cos(t); f2=@(t) sin(t);   
t_for_f=-pi:2^(-10):pi;
plot(f1(t_for_f),f2(t_for_f),'LineWidth',2)
hold on

% plot the sampled data points
plot(f_samples_semicircle(:,1),f_samples_semicircle(:,2), '.','MarkerSize',10,'Color','r','LineStyle','none')
axis equal
axis off

figure

% plot the deviation from the unit circle
plot(diff_wavy)
xlim([0, 128])
set(gca,'fontsize',24);

%% plot the oscillatory circle

figure

% plot the perfect unit cicrle
f1=@(t) cos(t); f2=@(t) sin(t);  
t_for_f=-pi:2^(-10):pi;
plot(f1(t_for_f),f2(t_for_f),'LineWidth',2)
hold on

% plot the sampled data points
plot(f_samples_noisycircle(:,1),f_samples_noisycircle(:,2), '.','MarkerSize',10,'Color','r','LineStyle','none')
axis equal
axis off

figure

% plot the deviation from the unit circle
plot(diff_noisy)
xlim([0, 128])
set(gca,'fontsize',24);

%% plot the NN cicrle

figure

% plot the perfect unit cicrle
f1=@(t) cos(t); f2=@(t) sin(t);   
t_for_f=-pi:2^(-10):pi;
plot(f1(t_for_f),f2(t_for_f),'LineWidth',2)
hold on

% plot the NN-generated sample points
plot(shifted_NN_samples(:,1),shifted_NN_samples(:,2), '.','MarkerSize',10,'Color','r','LineStyle','none')
axis equal
axis off

figure

% plot the deviation from the unit circle
plot(diff_NN)
xlim([0, 128])
ylim([-0.0015, 0.0013])
set(gca,'fontsize',24);